#!/bin/bash

./strip-image \
  -i u2126529/csvs2023-web_i \
  -v \
  -p epel-release \
  -p nginx \
  -p php \
  -p php-mysqlnd \
  -p php-fpm \
  -d Dockerfile \
  -t local/chat-stripped \
  -t u2126529/csvs2023-web_i:0.2


